<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Venue;
use App\Models\VenueCategory;
use App\Models\VenueStyle;
use App\Models\VenueType;
use Illuminate\Database\Seeder;

class VenueSeeder extends Seeder
{
    public function run(): void
    {
        $user = User::where('email', 'joao@demo.com')->firstOrFail();

        $types      = VenueType::whereNull('user_id')->get()->keyBy('name');
        $categories = VenueCategory::whereNull('user_id')->get()->keyBy('name');
        $styles     = VenueStyle::whereNull('user_id')
            ->where('domain', VenueStyle::DOMAIN_VENUES)
            ->get()
            ->keyBy('name');

        $typeBar      = $types->get('Bar');
        $typeCasa     = $types->get('Casa de show');
        $typeFestival = $types->get('Festival');

        $catIndie        = $categories->get('Indie');
        $catMainstream   = $categories->get('Mainstream');
        $catAlternativo  = $categories->get('Alternativo');

        $styleAcustico  = $styles->get('Acústico');
        $styleEletronico = $styles->get('Eletrônico');
        $styleVintage   = $styles->get('Vintage');

        // ─────────────────────────────────────────────
        // SP / ABC – Bares de música ao vivo
        // ─────────────────────────────────────────────
        $bares = [
            [
                'name'             => 'Blue Note SP',
                'phone'            => '(11) 94541-7570',
                'contact_name'     => 'Produção Blue Note',
                'address_line'     => 'Av. Paulista',
                'address_number'   => '2073',
                'neighborhood'     => 'Bela Vista',
                'city'             => 'São Paulo',
                'state'            => 'SP',
                'country'          => 'Brasil',
                'postal_code'      => '01310-100',
                'latitude'         => -23.5588,
                'longitude'        => -46.6606,
                'rating'           => 5,
                'status'           => 'open_doors',
                'performances_count' => 3,
                'equipment_tags'   => ['PA profissional', 'Monitor', 'Luz completa', 'Backline disponível'],
                'description'      => 'O Blue Note SP é o endereço do jazz e do blues de luxo em São Paulo. Acústica impecável, atendimento de primeira e público exigente.',
                'notes'            => 'Os Bisouros tocaram aqui em 2024. Cachê acima da média. Vale cada centavo.',
                'instagram_url'    => 'https://instagram.com/bluenotespbr',
                'website_url'      => 'https://bluenotejazz.com/saopaulo',
                'type'             => $typeBar,
                'category'         => $catMainstream,
                'style'            => $styleVintage,
            ],
            [
                'name'             => 'Bourbon Street',
                'phone'            => '(11) 5095-6100',
                'contact_name'     => 'Carlos da Produção',
                'address_line'     => 'R. dos Chanés',
                'address_number'   => '127',
                'neighborhood'     => 'Moema',
                'city'             => 'São Paulo',
                'state'            => 'SP',
                'country'          => 'Brasil',
                'postal_code'      => '04529-010',
                'latitude'         => -23.6086,
                'longitude'        => -46.6669,
                'rating'           => 5,
                'status'           => 'negotiating',
                'performances_count' => 2,
                'equipment_tags'   => ['PA', 'Monitor', 'Luz', 'Piano de cauda'],
                'description'      => 'Referência em rock, blues e pop em São Paulo. Palco intimista com ótima acústica.',
                'notes'            => 'Contrato para 3 shows em outubro aguardando assinatura. Carlos está com paciência de professor.',
                'instagram_url'    => 'https://instagram.com/bourbonstreetsp',
                'website_url'      => 'https://bourbonstreet.com.br',
                'type'             => $typeBar,
                'category'         => $catMainstream,
                'style'            => $styleVintage,
            ],
            [
                'name'             => 'Canto da Ema',
                'phone'            => '(11) 3813-4708',
                'contact_name'     => 'Roberto da Produção',
                'address_line'     => 'Av. Brig. Faria Lima',
                'address_number'   => '364',
                'neighborhood'     => 'Pinheiros',
                'city'             => 'São Paulo',
                'state'            => 'SP',
                'country'          => 'Brasil',
                'postal_code'      => '01452-000',
                'latitude'         => -23.5671,
                'longitude'        => -46.6901,
                'rating'           => 5,
                'status'           => 'contacted',
                'performances_count' => 1,
                'equipment_tags'   => ['PA', 'Monitor', 'Luz básica'],
                'description'      => 'Famoso bar com música ao vivo e forte identidade musical. MPB, samba e rock convivem bem aqui.',
                'notes'            => 'Ambiente aconchegante. Público fiel. Bingo adora a comida do bar.',
                'instagram_url'    => 'https://instagram.com/cantodaema',
                'type'             => $typeBar,
                'category'         => $catIndie,
                'style'            => $styleAcustico,
            ],
            [
                'name'             => 'O Garimpo',
                'phone'            => '(11) 4704-2740',
                'contact_name'     => 'Marlene da Produção',
                'address_line'     => 'R. Santana',
                'address_number'   => '32',
                'neighborhood'     => 'Centro Histórico',
                'city'             => 'Embu das Artes',
                'state'            => 'SP',
                'country'          => 'Brasil',
                'postal_code'      => '06806-020',
                'latitude'         => -23.6487,
                'longitude'        => -46.8522,
                'rating'           => 5,
                'status'           => 'contacted',
                'performances_count' => 0,
                'equipment_tags'   => ['PA', 'Monitor', 'Luz vintage'],
                'description'      => 'Bar cultural com décor boêmio e programação eclética em Embu das Artes. Frequentado por artistas e colecionadores.',
                'notes'            => 'Jorge ficou empolgado com as antiguidades na parede. Paulo ficou empolgado com o PA.',
                'instagram_url'    => 'https://instagram.com/ogarimp_embu',
                'type'             => $typeBar,
                'category'         => $catAlternativo,
                'style'            => $styleVintage,
            ],
            [
                'name'             => 'Grazie a Dio!',
                'phone'            => '(11) 3031-6568',
                'contact_name'     => 'Produção Grazie',
                'address_line'     => 'R. Girassol',
                'address_number'   => '67',
                'neighborhood'     => 'Vila Madalena',
                'city'             => 'São Paulo',
                'state'            => 'SP',
                'country'          => 'Brasil',
                'postal_code'      => '05433-000',
                'latitude'         => -23.5546,
                'longitude'        => -46.6894,
                'rating'           => 4,
                'status'           => 'undefined',
                'performances_count' => 0,
                'equipment_tags'   => ['PA compacto', 'Monitor'],
                'description'      => 'Bar clássico da Vila Madalena com shows de MPB e rock nacional às sextas e sábados.',
                'notes'            => 'Palco pequeno mas atmosfera incrível. Ideal para sets intimistas.',
                'instagram_url'    => 'https://instagram.com/grazieadio_sp',
                'type'             => $typeBar,
                'category'         => $catIndie,
                'style'            => $styleAcustico,
            ],
            // RJ – Bar
            [
                'name'             => 'Circo Voador',
                'phone'            => '(21) 2533-0354',
                'contact_name'     => 'Produção Circo',
                'address_line'     => 'R. dos Arcos',
                'address_number'   => 's/n',
                'neighborhood'     => 'Lapa',
                'city'             => 'Rio de Janeiro',
                'state'            => 'RJ',
                'country'          => 'Brasil',
                'postal_code'      => '20051-040',
                'latitude'         => -22.9126,
                'longitude'        => -43.1802,
                'rating'           => 5,
                'status'           => 'contacted',
                'performances_count' => 1,
                'equipment_tags'   => ['PA profissional', 'Monitor', 'Luz completa', 'Backline'],
                'description'      => 'Ícone cultural carioca debaixo dos arcos da Lapa. Um dos palcos mais icônicos do Brasil para rock independente.',
                'notes'            => 'Lotou quando tocamos. O João chorou de emoção. Oficialmente negou.',
                'instagram_url'    => 'https://instagram.com/circovoador',
                'website_url'      => 'https://circovoador.com.br',
                'type'             => $typeBar,
                'category'         => $catAlternativo,
                'style'            => $styleEletronico,
            ],
            // RS – Bar
            [
                'name'             => 'Opinião',
                'phone'            => '(51) 3211-2838',
                'contact_name'     => 'Daniela da Produção',
                'address_line'     => 'R. José do Patrocínio',
                'address_number'   => '834',
                'neighborhood'     => 'Cidade Baixa',
                'city'             => 'Porto Alegre',
                'state'            => 'RS',
                'country'          => 'Brasil',
                'postal_code'      => '90050-003',
                'latitude'         => -30.0418,
                'longitude'        => -51.2215,
                'rating'           => 5,
                'status'           => 'contacted',
                'performances_count' => 0,
                'equipment_tags'   => ['PA', 'Monitor', 'Luz', 'Camarim'],
                'description'      => 'Lendária casa de shows gaúcha, berço de grandes nomes da música brasileira.',
                'notes'            => 'Jorge queria usar o sitar aqui. Vetamos.',
                'instagram_url'    => 'https://instagram.com/opiniao_poa',
                'type'             => $typeBar,
                'category'         => $catAlternativo,
                'style'            => $styleVintage,
            ],
        ];

        // ─────────────────────────────────────────────
        // SP – Casas de Show
        // ─────────────────────────────────────────────
        $casasDeShow = [
            [
                'name'             => 'Espaço Unimed',
                'phone'            => '(11) 3868-5880',
                'contact_name'     => 'Fernanda da Produção',
                'address_line'     => 'R. Tagipuru',
                'address_number'   => '795',
                'neighborhood'     => 'Barra Funda',
                'city'             => 'São Paulo',
                'state'            => 'SP',
                'country'          => 'Brasil',
                'postal_code'      => '01156-000',
                'latitude'         => -23.5268,
                'longitude'        => -46.6685,
                'rating'           => 4,
                'status'           => 'negotiating',
                'performances_count' => 2,
                'equipment_tags'   => ['PA line array', 'Monitor', 'Luz completa', 'LED wall', 'Backline completo', 'Camarim VIP'],
                'description'      => 'Uma das principais casas de show de São Paulo. Capacidade para 5.000 pessoas, estrutura técnica de ponta.',
                'notes'            => 'Show marcado para maio. Passagem de som perdida (ver tarefa em aberto). Fernanda ainda nos atende, milagrosamente.',
                'instagram_url'    => 'https://instagram.com/espacounimed',
                'website_url'      => 'https://espacounimed.com.br',
                'type'             => $typeCasa,
                'category'         => $catMainstream,
                'style'            => $styleEletronico,
            ],
            [
                'name'             => 'Vibra São Paulo',
                'phone'            => '(11) 5644-0400',
                'contact_name'     => 'André da Produção',
                'address_line'     => 'Av. das Nações Unidas',
                'address_number'   => '17955',
                'neighborhood'     => 'Santo Amaro',
                'city'             => 'São Paulo',
                'state'            => 'SP',
                'country'          => 'Brasil',
                'postal_code'      => '04795-100',
                'latitude'         => -23.6453,
                'longitude'        => -46.7262,
                'rating'           => 5,
                'status'           => 'open_doors',
                'performances_count' => 4,
                'equipment_tags'   => ['PA line array', 'Monitor', 'Luz completa', 'LED wall', 'Backline', 'Camarim VIP', 'Área de hospitalidade'],
                'description'      => 'Maior casa de shows coberta da América Latina. Capacidade para 15.000 pessoas. Aqui os grandes acontecem.',
                'notes'            => 'Rider técnico atrasado. André está esperando com paciência budista.',
                'email'            => 'producao@vibraspaopaulo.com.br',
                'instagram_url'    => 'https://instagram.com/vibrasaopaulo',
                'website_url'      => 'https://vibrasaopaulo.com.br',
                'type'             => $typeCasa,
                'category'         => $catMainstream,
                'style'            => $styleEletronico,
            ],
            [
                'name'             => 'Audio',
                'phone'            => '(11) 3862-8279',
                'contact_name'     => 'Produção Audio Club',
                'address_line'     => 'Av. Francisco Matarazzo',
                'address_number'   => '694',
                'neighborhood'     => 'Água Branca',
                'city'             => 'São Paulo',
                'state'            => 'SP',
                'country'          => 'Brasil',
                'postal_code'      => '05001-100',
                'latitude'         => -23.5253,
                'longitude'        => -46.6672,
                'rating'           => 4,
                'status'           => 'contacted',
                'performances_count' => 1,
                'equipment_tags'   => ['PA', 'Monitor', 'Luz LED', 'Backline parcial'],
                'description'      => 'Casa de shows com foco em eletrônico e rock alternativo. Palco e pista integrados.',
                'notes'            => 'Bingo adorou o sistema de som. Disse que vai usar como referência para o álbum solo.',
                'instagram_url'    => 'https://instagram.com/audiosp',
                'type'             => $typeCasa,
                'category'         => $catAlternativo,
                'style'            => $styleEletronico,
            ],
            [
                'name'             => 'Carioca Club',
                'phone'            => '(11) 3813-8598',
                'contact_name'     => 'Larissa Carioca',
                'address_line'     => 'R. Cardeal Arcoverde',
                'address_number'   => '2899',
                'neighborhood'     => 'Pinheiros',
                'city'             => 'São Paulo',
                'state'            => 'SP',
                'country'          => 'Brasil',
                'postal_code'      => '05408-000',
                'latitude'         => -23.5701,
                'longitude'        => -46.6967,
                'rating'           => 4,
                'status'           => 'contacted',
                'performances_count' => 0,
                'equipment_tags'   => ['PA', 'Monitor', 'Luz'],
                'description'      => 'Tradicional casa de shows de Pinheiros com programação variada.',
                'notes'            => 'Larissa é eficiente e direta. Gostamos.',
                'instagram_url'    => 'https://instagram.com/cariocaclubsp',
                'type'             => $typeCasa,
                'category'         => $catIndie,
                'style'            => $styleVintage,
            ],
            // RJ – Casa de Show
            [
                'name'             => 'Vivo Rio',
                'phone'            => '(21) 2272-2900',
                'contact_name'     => 'Produção Vivo Rio',
                'address_line'     => 'Av. Infante Dom Henrique',
                'address_number'   => '85',
                'neighborhood'     => 'Aterro do Flamengo',
                'city'             => 'Rio de Janeiro',
                'state'            => 'RJ',
                'country'          => 'Brasil',
                'postal_code'      => '20021-140',
                'latitude'         => -22.9142,
                'longitude'        => -43.1764,
                'rating'           => 5,
                'status'           => 'open_doors',
                'performances_count' => 2,
                'equipment_tags'   => ['PA line array', 'Monitor', 'Luz completa', 'Vista para a Baía'],
                'description'      => 'Casa de shows com vista para a Baía de Guanabara. Uma das mais bonitas do Brasil.',
                'notes'            => 'Jorge pediu para ficar de frente para o Cristo. Impossível tecnicamente. Mas ele insistiu.',
                'instagram_url'    => 'https://instagram.com/vivoorio',
                'website_url'      => 'https://vivorio.com.br',
                'type'             => $typeCasa,
                'category'         => $catMainstream,
                'style'            => $styleVintage,
            ],
        ];

        // ─────────────────────────────────────────────
        // SP – Teatros
        // ─────────────────────────────────────────────
        $teatros = [
            [
                'name'             => 'Teatro Renault',
                'phone'            => '(11) 3572-5500',
                'contact_name'     => 'Produção Teatro Renault',
                'address_line'     => 'Av. Brigadeiro Luís Antônio',
                'address_number'   => '411',
                'neighborhood'     => 'Bela Vista',
                'city'             => 'São Paulo',
                'state'            => 'SP',
                'country'          => 'Brasil',
                'postal_code'      => '01317-000',
                'latitude'         => -23.5539,
                'longitude'        => -46.6397,
                'rating'           => 5,
                'status'           => 'contacted',
                'performances_count' => 0,
                'equipment_tags'   => ['PA profissional', 'Monitor', 'Luz teatral', 'Orquestra completa', 'Camarim VIP'],
                'description'      => 'Um dos teatros mais sofisticados do Brasil. Ideal para shows com orquestra ou apresentações especiais.',
                'notes'            => 'Paulo sonha em fazer um show sinfônico aqui. João disse que é caro demais. Paulo disse que vale.',
                'instagram_url'    => 'https://instagram.com/teatrorenault',
                'website_url'      => 'https://ticketmaster.com.br/teatro-renault',
                'type'             => $typeCasa,
                'category'         => $catMainstream,
                'style'            => $styleAcustico,
            ],
            [
                'name'             => 'Teatro Bradesco',
                'phone'            => '(11) 3670-4100',
                'contact_name'     => 'Produção Bradesco',
                'address_line'     => 'R. Palestra Itália',
                'address_number'   => '500',
                'neighborhood'     => 'Perdizes',
                'city'             => 'São Paulo',
                'state'            => 'SP',
                'country'          => 'Brasil',
                'postal_code'      => '05008-000',
                'latitude'         => -23.5262,
                'longitude'        => -46.6825,
                'rating'           => 4,
                'status'           => 'undefined',
                'performances_count' => 0,
                'equipment_tags'   => ['PA', 'Monitor', 'Luz teatral'],
                'description'      => 'Teatro dentro do Shopping Bourbon. Boa acústica, ótima localização.',
                'notes'            => 'Bingo sugere fazer um show especial de Natal aqui. Todos achamos que é boa ideia.',
                'instagram_url'    => 'https://instagram.com/teatrobradesco',
                'type'             => $typeCasa,
                'category'         => $catMainstream,
                'style'            => $styleAcustico,
            ],
        ];

        // ─────────────────────────────────────────────
        // SP – Centros Culturais
        // ─────────────────────────────────────────────
        $centrosCulturais = [
            [
                'name'             => 'Sesc Pompeia',
                'phone'            => '(11) 3871-7700',
                'contact_name'     => 'Cultura e Arte Sesc',
                'address_line'     => 'R. Clélia',
                'address_number'   => '93',
                'neighborhood'     => 'Pompeia',
                'city'             => 'São Paulo',
                'state'            => 'SP',
                'country'          => 'Brasil',
                'postal_code'      => '05042-000',
                'latitude'         => -23.5256,
                'longitude'        => -46.6847,
                'rating'           => 5,
                'status'           => 'contacted',
                'performances_count' => 1,
                'equipment_tags'   => ['PA', 'Monitor', 'Luz', 'Espaço diferenciado'],
                'description'      => 'Centro cultural icônico com arquitetura de Lina Bo Bardi. Teatro, galpões e espaços abertos para shows.',
                'notes'            => 'O galpão é lindo. Jorge ficou 20 minutos olhando para o teto. Inusitado.',
                'instagram_url'    => 'https://instagram.com/sescpompeia',
                'website_url'      => 'https://sesc.com.br',
                'type'             => $typeCasa,
                'category'         => $catIndie,
                'style'            => $styleAcustico,
            ],
        ];

        // ─────────────────────────────────────────────
        // Festivais
        // ─────────────────────────────────────────────
        $festivais = [
            [
                'name'             => 'Festival Estoque de Madeira',
                'phone'            => '(11) 98765-4321',
                'contact_name'     => 'Yoko Onodera',
                'address_line'     => 'Parque do Povo',
                'address_number'   => 's/n',
                'neighborhood'     => 'Campo Belo',
                'city'             => 'São Paulo',
                'state'            => 'SP',
                'country'          => 'Brasil',
                'postal_code'      => '04634-000',
                'email'            => 'yoko@estoquedemadeira.com.br',
                'latitude'         => -23.6201,
                'longitude'        => -46.6701,
                'rating'           => 5,
                'status'           => 'negotiating',
                'performances_count' => 0,
                'equipment_tags'   => ['PA line array', 'Monitor', 'Luz LED profissional', 'Backline completo', '2 palcos'],
                'description'      => 'Festival anual de rock e música independente em São Paulo. Atrai nomes nacionais e internacionais.',
                'notes'            => 'Rider precisa ser enviado até 25/04. Patrocinador: Cervejaria Revolução Acoustic.',
                'instagram_url'    => 'https://instagram.com/estoquedemadeira',
                'website_url'      => 'https://estoquedemadeira.com.br',
                'type'             => $typeFestival,
                'category'         => $catAlternativo,
                'style'            => $styleEletronico,
            ],
            [
                'name'             => 'Festival Montreux Brasil',
                'phone'            => '(21) 99876-5432',
                'contact_name'     => 'Produção Montreux BR',
                'address_line'     => 'Marina da Glória',
                'address_number'   => 's/n',
                'neighborhood'     => 'Glória',
                'city'             => 'Rio de Janeiro',
                'state'            => 'RJ',
                'country'          => 'Brasil',
                'postal_code'      => '20021-410',
                'latitude'         => -22.9241,
                'longitude'        => -43.1721,
                'rating'           => 5,
                'status'           => 'contacted',
                'performances_count' => 0,
                'equipment_tags'   => ['PA line array', 'Monitor', 'Luz completa', 'Palco flutuante'],
                'description'      => 'Versão brasileira do famoso festival suíço. Jazz, rock e fusões em cenário privilegiado.',
                'notes'            => 'Paulo tentou convencer a banda de que jazz e rock se misturam bem. Todos concordaram menos o Jorge.',
                'instagram_url'    => 'https://instagram.com/montreuxbrasil',
                'website_url'      => 'https://montreuxbrasil.com.br',
                'type'             => $typeFestival,
                'category'         => $catMainstream,
                'style'            => $styleVintage,
            ],
        ];

        // ─────────────────────────────────────────────
        // Outros (Brasil)
        // ─────────────────────────────────────────────
        $outros = [
            [
                'name'             => 'Teatro Amazonas',
                'phone'            => '(92) 3232-1768',
                'contact_name'     => 'Produção Teatro Amazonas',
                'address_line'     => 'Largo de São Sebastião',
                'address_number'   => 's/n',
                'neighborhood'     => 'Centro',
                'city'             => 'Manaus',
                'state'            => 'AM',
                'country'          => 'Brasil',
                'postal_code'      => '69025-040',
                'latitude'         => -3.1302,
                'longitude'        => -60.0234,
                'rating'           => 5,
                'status'           => 'undefined',
                'performances_count' => 0,
                'equipment_tags'   => ['PA histórico', 'Acústica natural', 'Orquestra'],
                'description'      => 'Um dos teatros mais belos do mundo, no coração da Amazônia. Sonho de qualquer artista.',
                'notes'            => 'João quer fazer um show especial aqui com orquestra. É caro. É difícil. Vamos tentar.',
                'instagram_url'    => 'https://instagram.com/teatroamazonas_am',
                'type'             => $typeCasa,
                'category'         => $catMainstream,
                'style'            => $styleAcustico,
            ],
            [
                'name'             => 'Auditório Araújo Vianna',
                'phone'            => '(51) 3211-2838',
                'contact_name'     => 'Produção Araújo Vianna',
                'address_line'     => 'Av. Osvaldo Aranha',
                'address_number'   => 's/n',
                'neighborhood'     => 'Farroupilha',
                'city'             => 'Porto Alegre',
                'state'            => 'RS',
                'country'          => 'Brasil',
                'postal_code'      => '90035-190',
                'latitude'         => -30.0381,
                'longitude'        => -51.2112,
                'rating'           => 5,
                'status'           => 'contacted',
                'performances_count' => 1,
                'equipment_tags'   => ['PA', 'Monitor', 'Luz', 'Anfiteatro ao ar livre'],
                'description'      => 'Clássico anfiteatro ao ar livre no Parque Farroupilha. Capacidade para 8.000 pessoas.',
                'notes'            => 'Paulo tocou aqui numa turnê solo (confidencial). Não contar ao João.',
                'instagram_url'    => 'https://instagram.com/araujoviannapoa',
                'type'             => $typeCasa,
                'category'         => $catAlternativo,
                'style'            => $styleAcustico,
            ],
            [
                'name'             => 'Dragão do Mar',
                'phone'            => '(85) 3488-8600',
                'contact_name'     => 'Cultura Dragão',
                'address_line'     => 'R. Dragão do Mar',
                'address_number'   => '81',
                'neighborhood'     => 'Praia de Iracema',
                'city'             => 'Fortaleza',
                'state'            => 'CE',
                'country'          => 'Brasil',
                'postal_code'      => '60060-390',
                'latitude'         => -3.7214,
                'longitude'        => -38.5197,
                'rating'           => 5,
                'status'           => 'contacted',
                'performances_count' => 0,
                'equipment_tags'   => ['PA', 'Monitor', 'Luz', 'Espaço aberto'],
                'description'      => 'Centro cultural com teatro, cinema, museus e espaços para shows. À beira-mar.',
                'notes'            => 'Bingo quer fazer um show descalço na areia aqui. Aprovado pela unanimidade da banda.',
                'instagram_url'    => 'https://instagram.com/dragaodomar',
                'type'             => $typeCasa,
                'category'         => $catAlternativo,
                'style'            => $styleAcustico,
            ],
            [
                'name'             => 'Instituto Inhotim',
                'phone'            => '(31) 3571-9700',
                'contact_name'     => 'Arte e Eventos Inhotim',
                'address_line'     => 'Rua B',
                'address_number'   => '20',
                'neighborhood'     => 'Centro',
                'city'             => 'Brumadinho',
                'state'            => 'MG',
                'country'          => 'Brasil',
                'postal_code'      => '35460-000',
                'latitude'         => -20.1252,
                'longitude'        => -44.2189,
                'rating'           => 5,
                'status'           => 'contacted',
                'performances_count' => 0,
                'equipment_tags'   => ['PA portátil', 'Natureza circundante', 'Arte contemporânea'],
                'description'      => 'Maior museu a céu aberto do Brasil, em meio à natureza de Minas Gerais.',
                'notes'            => 'Jorge quer apresentar seu manifesto filosófico aqui. Vetado. Mas um show ao ar livre seria lindo.',
                'instagram_url'    => 'https://instagram.com/institutoinhotim',
                'website_url'      => 'https://inhotim.org.br',
                'type'             => $typeCasa,
                'category'         => $catIndie,
                'style'            => $styleAcustico,
            ],
        ];

        $allVenues = array_merge($bares, $casasDeShow, $teatros, $centrosCulturais, $festivais, $outros);

        foreach ($allVenues as $venueData) {
            $venue = Venue::create([
                'user_id'            => $user->id,
                'name'               => $venueData['name'],
                'email'              => $venueData['email'] ?? null,
                'phone'              => $venueData['phone'],
                'contact_name'       => $venueData['contact_name'],
                'venue_type_id'      => $venueData['type']?->id,
                'venue_category_id'  => $venueData['category']?->id,
                'address_line'       => $venueData['address_line'],
                'address_number'     => $venueData['address_number'],
                'neighborhood'       => $venueData['neighborhood'],
                'city'               => $venueData['city'],
                'state'              => $venueData['state'],
                'postal_code'        => $venueData['postal_code'],
                'country'            => $venueData['country'],
                'latitude'           => $venueData['latitude'],
                'longitude'          => $venueData['longitude'],
                'status'             => $venueData['status'],
                'performances_count' => $venueData['performances_count'],
                'equipment_tags'     => $venueData['equipment_tags'],
                'rating'             => $venueData['rating'],
                'instagram_url'      => $venueData['instagram_url'] ?? null,
                'facebook_url'       => $venueData['facebook_url'] ?? null,
                'youtube_url'        => $venueData['youtube_url'] ?? null,
                'whatsapp'           => $venueData['whatsapp'] ?? null,
                'website_url'        => $venueData['website_url'] ?? null,
                'notes'              => $venueData['notes'],
                'description'        => $venueData['description'],
            ]);

            if ($venueData['style']) {
                $venue->styles()->sync([$venueData['style']->id]);
            }
        }
    }
}
